on:
  push:
  pull_request:
jobs:
  risk-groups:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn prettier --check .
      - run: yarn test:types
      - run: yarn risk-groups --dry
      - name: "All changes comitted?"
        run: git diff --exit-code
