on:
  schedule:
    # https://crontab.guru/#0_*_*_*_*
    - cron: "0 * * * *"
jobs:
  risk-groups:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn risk-groups
        env:
          ELIGIBLE_GROUPS_UPDATED_HOOK: ${{ secrets.ELIGIBLE_GROUPS_UPDATED_HOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Upload eligible groups
        run: |
          aws s3 sync data s3://vax-notify/data --exclude='*' --include='*/eligibleGroups.json'
