on:
  schedule:
    # https://crontab.guru/#0_*_*_*_*
    - cron: "0 * * * *"
jobs:
  risk-groups:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn risk-groups
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
